### ISSUE TITLE
Lora data not being transmitted

### ISSUE THREAD

**Issue by mauriceatkinson** [sighmon/water-quality-lorawan-dragino-pi#4] opened 2022-04-13 10:25 UTC
@sighmon I have opended a new issue to keep this separate and hopefully not to confuse things.
In the rasp pi logs I am seeing the sensor readings taking place every 15 minutes and it indicates the sensor readings are being transferred over lora.  

However on my lora wan gateway and the TTN console I am not seeing every message the rasp pi shows it is transmitting.  The logs below show fcnt 1996 and fcnt 1994 that are missing.  I have just shown these two messages missing but it is a regualr occurance with many messages not being received.

The link gives you access to the log files  https://drive.google.com/drive/folders/1cHFf9MOTQUQjSvfz3X5BP_q5q7KFV0ct?usp=sharing

pi_testlog - raspberry pi log file
packet_log..csv - my lora gateway
eui...json - ttn console end device live data log

**Comment by sighmon** [comment] 2022-04-13 13:36
@mauriceatkinson I've requested to view the log files, but in the meantime we could try re-joining before sending each time and see if that helps.

Try: `git pull` and see if anything changes.

But yes, the problem is with the `dragino` library, so you'd have to ask them to handle the error you're seeing. They may have some other suggestions of how to avoid it too.

**Comment by mauriceatkinson** [comment] 2022-04-13 18:41
@sighmon this change looks to be a backward step as now lots of packets are missing and no data is being forwarded by TTN via mqtt.  Could you reverse this change?

I have made contact with the dragino developer so lets see what they say.

**Comment by sighmon** [comment] 2022-04-13 22:34
@mauriceatkinson No problems - I've reverted that change now. So do another `git pull`. Fingers crossed the developers come back with a solution.

**Comment by mauriceatkinson** [comment] 2022-04-14 08:27
@sighmon thanks.  I contacted the developer and he found a problem so currently I am testing this out.  As I have got his attention I will raise the Duty Cycle issue as well.

**Comment by sighmon** [comment] 2022-04-17 00:22
Fixed via https://github.com/BNNorman/dragino-1/commit/16b17dd33c2e2b9e4b727c5ace4479214d460578

**Closed as completed by sighmon** 2022-04-17 00:22 UTC
